# Generated by Django 5.1.6 on 2025-04-09 14:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('codigo_evidencias', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateField()),
                ('direccion', models.CharField(max_length=45)),
                ('evidencias', models.TextField()),
                ('evidencias_fotograficas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='FaunaYFlora',
            fields=[
                ('codigo', models.AutoField(primary_key=True, serialize=False)),
                ('especie', models.CharField(choices=[('Fauna', 'Fauna'), ('Flora', 'Flora')], max_length=10)),
                ('nombre', models.CharField(max_length=45)),
                ('estado', models.CharField(max_length=45)),
                ('caracteristicas', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('codigo_roles', models.AutoField(primary_key=True, serialize=False)),
                ('rol', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Zonas',
            fields=[
                ('codigo_zonas', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('responsable', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.IntegerField()),
                ('correo', models.CharField(max_length=45)),
                ('contraseña', models.CharField(max_length=45)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zonas')),
            ],
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('codigo_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('ubicacion', models.CharField(max_length=45)),
                ('evidencia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.evidencia')),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
        ),
        migrations.AddField(
            model_name='evidencia',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario'),
        ),
        migrations.CreateModel(
            name='Emergencia',
            fields=[
                ('codigo_e', models.AutoField(primary_key=True, serialize=False)),
                ('tipo_e', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
                ('fecha', models.CharField(max_length=45)),
                ('gravedad', models.CharField(max_length=45)),
                ('usuario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.usuario')),
            ],
        ),
        migrations.CreateModel(
            name='EvidenciasFaunaFlora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencia')),
                ('fauna_flora', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.faunayflora')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
            options={
                'unique_together': {('evidencia', 'usuario', 'fauna_flora')},
            },
        ),
    ]
