# Generated by Django 5.1.6 on 2025-04-10 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
          migrations.CreateModel(
            name='Zona',
            fields=[
                ('codigo_zonas', models.AutoField(primary_key=True)),
                ('nombre', models.CharField(max_length=45)),
                ('responsable', models.CharField(max_length=45)),
                ('ubicacion', models.CharField(max_length=45)),
            ],
        ),
        migrations.RenameModel(
            old_name='Zonas',
            new_name='Zona',
        ),
        migrations.RemoveField(
            model_name='evidencia',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='evidencia',
        ),
        migrations.RemoveField(
            model_name='evidenciasfaunaflora',
            name='evidencia',
        ),
        migrations.AlterUniqueTogether(
            name='evidenciasfaunaflora',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='evidenciasfaunaflora',
            name='fauna_flora',
        ),
        migrations.RemoveField(
            model_name='evidenciasfaunaflora',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='ubicacion',
            name='usuario',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='zona',
        ),
        migrations.DeleteModel(
            name='Emergencia',
        ),
        migrations.DeleteModel(
            name='Evidencia',
        ),
        migrations.DeleteModel(
            name='FaunaYFlora',
        ),
        migrations.DeleteModel(
            name='EvidenciasFaunaFlora',
        ),
        migrations.DeleteModel(
            name='Ubicacion',
        ),
        migrations.DeleteModel(
            name='Usuario',
        ),
    ]
