# Generated by Django 5.1.6 on 2025-04-11 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ubicacion'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evidencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('caracteristicas', models.CharField(max_length=450)),
                ('direccion', models.CharField(max_length=200)),
                ('fecha', models.DateField()),
                ('ubicacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ubicacion')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.usuario')),
            ],
        ),
    ]
