# Generated by Django 5.1.6 on 2025-04-10 16:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_zonas_zona_remove_evidencia_usuario_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('cedula', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=45)),
                ('apellido', models.CharField(max_length=45)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=45)),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.rol')),
                ('zona', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.zona')),
            ],
        ),
    ]
