# Generated by Django 5.1.6 on 2025-04-11 14:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evidencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='FaunaFlora',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=80)),
                ('especie', models.CharField(choices=[('Fauna', 'Fauna'), ('Flora', 'Flora')], max_length=10)),
                ('estado', models.CharField(max_length=250)),
                ('caracteristicas', models.CharField(max_length=300)),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencia')),
            ],
        ),
    ]
