# Generated by Django 5.1.6 on 2025-04-11 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_faunaflora'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=40)),
                ('descripcion', models.CharField(max_length=250)),
                ('link_imagen', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField()),
                ('evidencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.evidencia')),
            ],
        ),
    ]
